version: "3.8"

services:
  taskie-backend:
    image: taskie-backend
    ports:
      - "8000:8000"
    environment:
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      TSK_DB_URL: "${TSK_DB_URL}"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      TZ: "${TZ}"

volumes:
  postgres_data:
