services:
  taskie-backend:
    image: taskie-backend
    ports:
      - "88:8000"
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      TSK_DB_URL: ${TSK_DB_URL}
    depends_on:
      - postgres
    restart: unless-stopped
    
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: taskie_test_db
  
volumes:
  postgres_data:
