services:
  taskie-backend:
    image: taskie-backend
    ports:
      - "8000:8000"
    environment:
      JWT_SECRET_KEY: "secret_key"
      TSK_DB_URL: "postgresql://testuser:testpass@postgres:5432/taskie_dev_db"
    depends_on:
      - postgres
    restart: unless-stopped
    
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: taskie_dev_db
  
volumes:
  postgres_data:
