INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT"
VALUE_TOO_SHORT = "VALUE_TOO_SHORT"
VALUE_TOO_LONG = "VALUE_TOO_LONG"
INVALID_DATE_FORMAT = "INVALID_DATE_FORMAT"
VALUE_MUST_NOT_BE_EMPTY = "VALUE_MUST_NOT_BE_EMPTY"
INVALID_VALUE_RANGE = "INVALID_VALUE_RANGE"
DUPLICATED_VALUE = "DUPLICATED_VALUE"
START_DATE_GREATER_THAN_END_DATE = "START_DATE_GREATER_THAN_END_DATE"


USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
INCORRECT_USERNAME_OR_PASSWORD = "INCORRECT_USERNAME_OR_PASSWORD"

INVALID_CREDENTIAL = "INVALID_CREDENTIAL"
EXPIRED_TOKEN = "EXPIRED_TOKEN"

DATA_DOES_NOT_EXIST = "DATA_DOES_NOT_EXIST"

# signup
PASSWORD_NOT_MATCH = "PASSWORD_NOT_MATCH"

# update user
USERNAME_CANNOT_BE_CHANGED = "USERNAME_CANNOT_BE_CHANGED"
