name: Taskie tests

on:
  push:
    tags: ["*"]
  pull_request:
    types: [ready_for_review, opened, reopened, auto_merge_enabled]


jobs:
  Run-and-Test:
    runs-on: ubuntu-latest
    
    env:
      TSK_SQLALCHEMY_URL: "sqlite:///./db/taskie_test.db"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ^3.10

    - name: Install poetry
      run: |
        pip install poetry
    
    - name: Install dependencies
      run: |
        poetry install
        
    - name: Run env
      run: |
        poetry shell

    - name: Set up the database folder
      run: |
        mkdir db
        echo "Initializing the database..."

    - name: Run tests
      run: |
        pytest tests -v
