name: Taskie tests

on:
  push:
    tags: ["*"]
  pull_request:
    types: [ready_for_review, opened, reopened, auto_merge_enabled]

jobs:
  Run-and-Test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: taskie_test_db
          TZ: Asia/Seoul
        ports:
          - 5432:5432

    env:
      TSK_DB_URL: "postgresql://testuser:testpass@localhost:5432/taskie_test_db"
      JWT_SECRET_KEY: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.9

      - name: Install poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Test with pytest
        run: |
          poetry run pytest
